# Generated by Django 4.0 on 2022-06-09 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean_code',
            field=models.CharField(default=0, max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
            preserve_default=False,
        ),
    ]
