# Generated by Django 4.0 on 2022-06-09 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_ean_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean_code',
            field=models.CharField(max_length=19, validators=[django.core.validators.MinLengthValidator(19)]),
        ),
    ]
